<#assign hasPrimaryKey = false />
<#list table.columnList as column>
	<#if column.primaryKey>
		<#assign hasPrimaryKey = true>
		<#break>
	</#if>
</#list>
package ${package};

import java.util.ArrayList;
import java.util.List;

import org.sosostudio.dbking.DbKing;
import org.sosostudio.dbking.Row;
import org.sosostudio.dbking.RowSet;
import org.sosostudio.dbking.autocode.PaginationArrayList;
import org.sosostudio.dbking.oom.ConditionClause;
import org.sosostudio.dbking.oom.DeleteSql;
import org.sosostudio.dbking.oom.ExtraClause;
import org.sosostudio.dbking.oom.InsertKeyValueClause;
import org.sosostudio.dbking.oom.InsertSql;
import org.sosostudio.dbking.oom.LogicalOp;
import org.sosostudio.dbking.oom.OrderByClause;
import org.sosostudio.dbking.oom.RelationOp;
import org.sosostudio.dbking.oom.SelectSql;
import org.sosostudio.dbking.oom.UpdateKeyValueClause;
import org.sosostudio.dbking.oom.UpdateSql;

/**
 * ${table.name}
 *
 * @author generated by dbking autocode
 */
public class ${table.definationName}Dao {

	private DbKing dbKing;

	public ${table.definationName}Dao() {
		dbKing = new DbKing();
	}
	
	public ${table.definationName}Dao(DbKing dbKing) {
		this.dbKing = dbKing;
	}

	<#if table.table>
	public int add${table.definationName}(${table.definationName} ${table.variableName}) {
		${table.variableName}.truncateString();
		InsertSql insertSql = new InsertSql().setTableName(${table.definationName}.${table.name})
			.setInsertKeyValueClause(
				new InsertKeyValueClause()
		<#list table.columnList as column>
					.add${column.type.getName()}Clause(${table.definationName}.${column.name}, ${table.variableName}.get${column.definationName}())
		</#list>
		);
		return dbKing.executeInsertSql(insertSql);
	}

	<#if hasPrimaryKey>
	public int update${table.definationName}(${table.definationName} ${table.variableName}) {
		${table.variableName}.truncateString();
		UpdateSql updateSql = new UpdateSql().setTableName(${table.definationName}.${table.name})
			.setUpdateKeyValueClause(
				new UpdateKeyValueClause()
		<#list table.columnList as column>
					.add${column.type.getName()}Clause(${table.definationName}.${column.name}, ${table.variableName}.get${column.definationName}())
		</#list>
			).setConditionClause(
				new ConditionClause(LogicalOp.AND)
		<#list table.columnList as column>
			<#if column.primaryKey>
				.add${column.type.getName()}Clause(${table.definationName}.${column.name}, RelationOp.EQUAL, ${table.variableName}.get${column.definationName}())
			</#if>
		</#list>	
			);
		return dbKing.executeUpdateSql(updateSql);
	}
	</#if>

	public int update${table.definationName}(UpdateKeyValueClause updateKeyValueClause, ConditionClause conditionClause) {
		UpdateSql updateSql = new UpdateSql().setTableName(${table.definationName}.${table.name})
			.setUpdateKeyValueClause(updateKeyValueClause)
			.setConditionClause(conditionClause);
		return dbKing.executeUpdateSql(updateSql);
	}
	
	public int delete${table.definationName}(ConditionClause conditionClause) {
		DeleteSql deleteSql = new DeleteSql().setTableName(${table.definationName}.${table.name})
			.setConditionClause(conditionClause);
		return dbKing.executeDeleteSql(deleteSql);
	}
	</#if>

	public PaginationArrayList<${table.definationName}> query${table.definationName}(ConditionClause conditionClause, ExtraClause extraClause, OrderByClause orderByClause, int pageSize, int pageNumber) {
		SelectSql selectSql = new SelectSql().setTableName(${table.definationName}.${table.name})
			.setColumns("*")
			.setConditionClause(conditionClause)
			.setExtraClause(extraClause)
			.setOrderByClause(orderByClause);
		RowSet rowSet = dbKing.executeSelectSql(selectSql, pageSize, pageNumber);
		PaginationArrayList<${table.definationName}> pal = new PaginationArrayList<${table.definationName}>(rowSet.getPageSize(), rowSet.getPageNumber(), rowSet.getTotalRowCount());
		for (Row row : rowSet) {
			${table.definationName} ${table.variableName} = new ${table.definationName}();
			<#list table.columnList as column>
			${table.variableName}.set${column.definationName}(row.get${column.type.getName()}(${table.definationName}.${column.name}));
			</#list>
			pal.add(${table.variableName});
		}
		return pal;
	}

	public List<${table.definationName}> query${table.definationName}(ConditionClause conditionClause, ExtraClause extraClause, OrderByClause orderByClause) {
		SelectSql selectSql = new SelectSql().setTableName(${table.definationName}.${table.name})
			.setColumns("*")
			.setConditionClause(conditionClause)
			.setExtraClause(extraClause)
			.setOrderByClause(orderByClause);
		RowSet rowSet = dbKing.executeSelectSql(selectSql);
		ArrayList<${table.definationName}> al = new ArrayList<${table.definationName}>();
		for (Row row : rowSet) {
			${table.definationName} ${table.variableName} = new ${table.definationName}();
			<#list table.columnList as column>
			${table.variableName}.set${column.definationName}(row.get${column.type.getName()}(${table.definationName}.${column.name}));
			</#list>
			al.add(${table.variableName});
		}
		return al;
	}

}